# Generated by Django 3.0 on 2024-11-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=500)),
                ('narration', models.CharField(max_length=500)),
                ('date_reported', models.DateField()),
                ('date_occured', models.DateField()),
                ('place', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('pin', models.CharField(max_length=40)),
                ('post', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('arrest', models.CharField(max_length=20)),
                ('charges', models.CharField(max_length=20)),
                ('conviction', models.CharField(max_length=20)),
                ('stolen_items', models.CharField(max_length=200)),
                ('file', models.CharField(max_length=100)),
                ('fir', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='victim_or_suspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('pin', models.CharField(max_length=40)),
                ('adharno', models.CharField(max_length=40)),
                ('photo', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('CASE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Case')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('pin', models.CharField(max_length=40)),
                ('adharno', models.CharField(max_length=40)),
                ('photo', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('qualification', models.CharField(max_length=40)),
                ('place', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('pin', models.CharField(max_length=40)),
                ('adharno', models.CharField(max_length=40)),
                ('photo', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Evidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date_collected', models.DateField()),
                ('collected_by', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('land_mark', models.CharField(max_length=50)),
                ('storage_location', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
                ('CASE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date_reported', models.DateField()),
                ('date_occured', models.DateField()),
                ('place', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('pin', models.CharField(max_length=40)),
                ('post', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chat', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='myapp.Login')),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='myapp.Login')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='INVESTIGATOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Investigator'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('COMPLAINT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Complaint')),
                ('INVESTIGATOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Investigator')),
            ],
        ),
    ]
